# ==============================================================================
# FILE: config/logging_config.yaml
# ==============================================================================
# Logging configuration for SFC integration

logging:
  version: 1
  disable_existing_loggers: false
  
  formatters:
    standard:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
    
    detailed:
      format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: standard
      stream: ext://sys.stdout
    
      file:
        class: logging.handlers.RotatingFileHandler  # Better handler
        level: DEBUG
        formatter: detailed
        filename: 'logs/sfc_kalman.log'
        mode: 'a'
        maxBytes: 10485760  # 10MB
        backupCount: 5
        # Create directory if doesn't exist
        delay: true  # Don't create file until first log
    
    error_file:
      class: logging.FileHandler
      level: ERROR
      formatter: detailed
      filename: 'logs/sfc_errors.log'
      mode: 'a'
  
  loggers:
    # SFC components
    src.models.unified_sfc_kalman:
      level: DEBUG
      handlers: [console, file]
      propagate: false
    
    src.network.fwtw_z1_mapper:
      level: INFO
      handlers: [console, file]
      propagate: false
    
    src.utils.network_discovery:
      level: INFO
      handlers: [console, file]
      propagate: false
    
    # Parent Kalman filter
    models.hierarchical_kalman_filter:
      level: INFO
      handlers: [console, file]
      propagate: false
  
  root:
    level: INFO
    handlers: [console, file, error_file]
    
    setup:
      create_directories:
        - 'logs'
        - 'output/diagnostics'
        - 'cache/fwtw'    
