# Stock-Flow Consistent Kalman Filter Configuration
# Simplified version that works with the fixed implementation

sfc:
  # Core settings
  enforce_sfc: true                    # Enable stock-flow consistency
  enforce_market_clearing: true        # Enable market clearing constraints
  bilateral_weight: 0.3                 # Weight for bilateral constraints
  error_variance_ratio: 0.01           # Measurement error ratio
  normalize_data: true                 # Normalize before filtering
  transformation: 'square'              # Transformation type for hierarchy
  
  # Data limits
  max_series: 500                      # Maximum number of series to process
  
  # Output settings
  output_dir: './output'               # Base output directory
  create_visualizations: true          # Generate plots
  
  # Data paths
  cache_dir: './data/cache'            # Cache directory for data
  base_dir: './data/fed_data'          # Base directory for Fed data
  
  # Formula settings (optional)
  enforce_formulas: false              # Disable if no formula file exists
  formula_path: './data/fof_formulas_extracted.json'  # Path to formulas

# Run mode configurations
# These override the base settings above
run_modes:
  # Quick test mode - minimal data
  test:
    max_series: 50                    # Use only 50 series
    enforce_market_clearing: false    # Disable market clearing for speed
    enforce_formulas: false           # Skip formula constraints
    create_visualizations: false      # Skip visualizations for speed
    
  # Development mode - moderate data  
  development:
    max_series: 200                   # Use 200 series
    enforce_sfc: true                 # Keep SFC constraints
    enforce_formulas: false           # Skip formulas if issues
    constraint_method: 'soft'         # Use soft constraints (faster)
    
  # Production mode - full data
  production:
    max_series: 500                   # Use up to 500 series  
    enforce_sfc: true                 # Full SFC enforcement
    enforce_market_clearing: true     # Full market clearing
    enforce_formulas: false           # Enable if formula file exists
    constraint_method: 'exact'        # Exact constraint enforcement
    
  # Large mode - maximum data (if memory permits)
  large:
    max_series: 1000                  # Use up to 1000 series
    enforce_sfc: true
    enforce_market_clearing: true
    use_sparse_matrices: true         # Use sparse matrices for memory

# Series selection priorities
# Which series to prioritize when limiting data
series_priorities:
  # Priority 1: Complete stock-flow pairs
  prioritize_pairs: true              # Select FL-FU pairs together
  
  # Priority 2: Important sectors (from Z.1 documentation)
  priority_sectors:
    - '10'  # Nonfinancial corporate business
    - '15'  # Households and nonprofit organizations  
    - '26'  # Rest of the world
    - '31'  # Federal government
    - '70'  # Private depository institutions
    - '89'  # All sectors (totals)
    - '90'  # Instrument discrepancies
    
  # Priority 3: Important instruments
  priority_instruments:
    - '30641'  # Corporate equities
    - '31305'  # Treasury securities
    - '40005'  # Consumer credit

# Validation tolerances
# How close constraints must be satisfied
validation:
  stock_flow:
    relative_tolerance: 1e-6          # Very tight for accounting
    absolute_tolerance: 1.0           # $1M USD
    
  bilateral:
    relative_tolerance: 0.05          # 5% for FWTW measurement error
    absolute_tolerance: 100           # $100M USD
    
  market_clearing:
    relative_tolerance: 0.02          # 2% acceptable
    absolute_tolerance: 1000          # $1B USD
    
  formula:
    relative_tolerance: 0.001         # 0.1% for formulas
    absolute_tolerance: 100           # $100M USD

# Performance tuning
performance:
  use_sparse_matrices: false          # Use sparse matrices (memory vs speed)
  chunk_size: 1000                    # Process in chunks if needed
  parallel_processing: false          # Use parallel processing
  n_jobs: -1                          # Number of parallel jobs (-1 = all cores)
  
# Logging settings  
logging:
  level: 'INFO'                       # Logging level: DEBUG, INFO, WARNING, ERROR
  file: null                          # Log file path (null = console only)
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  
# Cache settings
cache:
  enabled: true                       # Use caching
  expire_hours: 168                  # Cache expiry (1 week)
  compression: 'snappy'               # Compression: none, snappy, gzip
  
# Output formats
output:
  save_filtered: true                 # Save filtered states
  save_smoothed: true                 # Save smoothed states  
  save_diagnostics: true              # Save constraint diagnostics
  format: 'parquet'                   # Output format: csv, parquet
  compression: 'snappy'               # Output compression
