# ==============================================================================
# FILE: config/sfc_config.yaml
# ==============================================================================
# Main configuration for Stock-Flow Consistent Kalman Filter
# Updated for full SFC implementation with constraint projection

version: '2.0'  # Updated version for new SFC system
environment: '${SFC_ENV:-development}'

sfc:
  # Data sources with proper paths and validation
  data_sources:
    # Base directory can be overridden with environment variable
    base_directory: '${SFC_PROJECT_ROOT:-.}'
    
    z1_data:
      source_type: 'federal_reserve_z1'
      cache_directory: '${SFC_PROJECT_ROOT:-.}/data/cache/z1'
      raw_directory: '${SFC_PROJECT_ROOT:-.}/data/raw/z1'
      file_pattern: 'Z1_*.xml'
      required: true
      
    fwtw_data:
      source_type: 'federal_reserve_fwtw'
      url: 'https://www.federalreserve.gov/releases/efa/fwtw_data.csv'
      cache_directory: '${SFC_PROJECT_ROOT:-.}/data/cache/fwtw'
      cache_file: 'fwtw_data.parquet'
      cache_expiry_hours: 168  # 1 week
      required: false  # Can run without FWTW
      
    formulas:
      primary_path: '${SFC_PROJECT_ROOT:-.}/data/fof_formulas_extracted.json'
      backup_path: '${SFC_PROJECT_ROOT:-.}/data/fof_formulas_backup.json'
      validation_required: false  # Set to false if file doesn't exist
      allow_missing: true  # Allow missing formulas
  
  # SFC enforcement settings (NEW STRUCTURE)
  enforcement:
    # Master switch for SFC constraints
    enforce_sfc: true  # Enable full stock-flow consistency
    
    # Individual constraint types
    stock_flow_consistency:
      enforce: true
      method: 'exact'  # 'exact' or 'soft'
      weight: 1.0  # Weight for soft constraints (ignored for exact)
      
    bilateral_consistency:
      enforce: true
      method: 'soft'  # FWTW data has measurement error
      weight: 0.3
      
    market_clearing:
      enforce: true
      method: 'soft'  # Allow small discrepancies
      weight: 0.1
      by_instrument: true
      
    formulas:
      enforce: false  # Set to true if you have formulas
      strict: false
      
    fwtw:
      enforce: true
      require_overlap: false
      min_overlap_fraction: 0.0  # Accept any overlap
      include_all: true
  
  # Constraint weights for projection (NEW)
  constraints:
    # Weights for different constraint types in projection
    stock_flow_weight: 0.5  # Weight for stock-flow identity
    bilateral_weight: 0.3   # Weight for FWTW bilateral flows
    fwtw_weight: 0.3       # Weight for FWTW positions
    market_clearing_weight: 0.1  # Weight for market clearing
    
    # Projection settings
    projection:
      method: 'exact'  # 'exact' or 'weighted'
      regularization: 1e-10  # Numerical stability
      max_iterations: 100  # For iterative solvers
      tolerance: 1e-8
      use_sparse: true  # Use sparse matrices for large systems
  
  # Kalman filter parameters
  kalman:
    # State space configuration
    state_space:
      include_flows: true  # Include flow states (NEW)
      include_trends: true  # Include trend components
      error_variance_ratio: 0.01
      normalize_data: true
      normalization_method: 'global_median'
      transformation: 'square'  # or 'log'
      
    initialization:
      method: 'diffuse'
      loglikelihood_burn: 10
      use_exact_diffuse: false
      
    optimization:
      max_iterations: 1000
      tolerance: 1e-8
      method: 'lbfgs'
  
  # Performance settings (UPDATED)
  performance:
    # Series selection and limiting
    max_series: 500  # Maximum series to process (memory limit)
    prioritize_pairs: true  # Prioritize stock-flow pairs
    priority_sectors:  # Sectors to prioritize
      - '10'  # Nonfinancial corporate
      - '15'  # Households
      - '26'  # Rest of world
      - '31'  # Federal government
      - '40'  # Financial sector aggregate
      - '70'  # Private depository institutions
      - '89'  # All sectors
      - '90'  # Instrument discrepancies
    
    # Memory management
    memory:
      max_series_in_memory: 500  # Reduced for SFC complexity
      chunk_size: 100  # Process in chunks if needed
      use_sparse_matrices: true  # Use sparse for constraints
      
    # Computational settings
    parallel:
      enable: false
      n_jobs: -1
      
    caching:
      enable: true
      cache_directory: '${SFC_PROJECT_ROOT:-.}/cache'
      cache_processed_data: true
      cache_filter_results: false
  
  # Validation settings (UPDATED)
  validation:
    # Stock-flow consistency tolerance
    stock_flow:
      relative_tolerance: 1e-6  # Very tight for accounting identity
      absolute_tolerance: 1.0   # $1M USD
      check_every_period: true
      
    # Bilateral consistency tolerance  
    bilateral:
      relative_tolerance: 0.05  # 5% for FWTW measurement error
      absolute_tolerance: 100   # $100M USD
      
    # Market clearing tolerance
    market_clearing:
      relative_tolerance: 0.02  # 2% acceptable
      absolute_tolerance: 1000  # $1B USD
      
    # Formula constraints (if used)
    formula_constraints:
      relative_tolerance: 0.001
      absolute_tolerance: 100
      
    # Validation actions
    actions:
      log_warnings: true
      fail_on_violation: false
      save_diagnostics: true
      diagnostic_level: 'detailed'  # 'summary', 'detailed', 'verbose'
      report_frequency: 10  # Report every N time periods
  
  # Output configuration
  output:
    # Output directory (simplified)
    output_dir: './output'
    
    # What to save
    save_filtered: true
    save_smoothed: true
    save_bilateral_flows: true  # NEW: Save calculated bilateral flows
    save_constraint_diagnostics: true  # NEW: Save constraint validation
    
    # Output formats
    format: 'csv'  # 'csv' or 'parquet'
    compression: null  # null, 'gzip', 'bz2'
    
    # Output options
    denormalize: true  # Convert back to original scale
    include_metadata: true
    save_intermediate: false
    
    # Diagnostic outputs (NEW)
    diagnostics:
      save_constraint_violations: true
      save_projection_adjustments: true
      save_state_evolution: false  # Large file
      plot_constraint_satisfaction: true

# Run modes for different use cases
run_modes:
  # Quick test with limited data
  test:
    sfc:
      performance:
        max_series: 50
      enforcement:
        enforce_sfc: true
      validation:
        diagnostic_level: 'verbose'
        
  # Development with moderate data
  development:
    sfc:
      performance:
        max_series: 200
      enforcement:
        enforce_sfc: true
        stock_flow_consistency:
          method: 'soft'  # Faster for development
          
  # Production with full constraints
  production:
    sfc:
      performance:
        max_series: 500
      enforcement:
        enforce_sfc: true
        stock_flow_consistency:
          method: 'exact'  # Exact for production
      validation:
        diagnostic_level: 'detailed'
        
  # Large scale (if memory permits)
  large:
    sfc:
      performance:
        max_series: 1000
        memory:
          use_sparse_matrices: true
      constraints:
        projection:
          use_sparse: true
